spring:
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  application:
    buckedName: example_data_vaccine
    kind: Vaccine

server:
  port: 8010
